id: Jester
team: Neutral
categories:
  - Neutral Benign
color: "#FCA8FC"
ability:
  murder_descriptions:
    - "They apparently shot themselves. Their suicide note expressed grief and guilt over the Jester's death"