- name: Dragon Head
  team: Triad
  summary: '489 - "Dragon Master" - The cunning and masterful leader of the Triad chapter.'
  goal: "Kill off the Town and everyone else who would oppose you."
  categories:
  - Triad Killing
  color: "#9F8EFF"
  ability:
    description: "Order to kill, Kill."