id: Bodyguard
team: Town
summary: "A war veteran who secretly makes a living by selling protection."
goal: "Lynch every criminal and evildoer."
categories:
- Town Protective
- Town Killing
color: "#00CC66"
ability:
  description: "Guard one player each night. If someone attacks a guarded player, both the attacker and the Bodyguard die instead of the guarded player."
  murder_descriptions:
  - "They were killed in a duel."
  - "They were slain in a shootout."