id: Bodyguard
team: Town
categories:
- Town Protective
original_categories:
- Town Protective
- Town Killing
color: "#00CC66"
ability:
  murder_descriptions:
  - "They were killed in a duel."
  - "They were slain in a shootout."