id: Bus Driver
team: Town
categories:
  - Town Protective
original_categories:
  - Town Protective
  - Town Power
color: "#55CC11"
abilities:
  - Ride
ability:
  murder_descriptions:
    - "They were run over by a bus."