id: Veteran
team: Town
categories:
- Town Killing
- Town Power
color: "#AAFF55"
ability:
  murder_descriptions:
  - "They were killed with a military-grade assault rifle."
  - "They had multiple wounds from a fragmentation grenade. They were killed with a military-grade assault rifle."